# Generated by Django 2.2.4 on 2019-11-21 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('venue', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField(verbose_name='start time and date')),
                ('end_time', models.DateTimeField(verbose_name='end time and date')),
                ('short_description', models.CharField(max_length=100)),
                ('event_description', models.TextField(max_length=600)),
                ('event_image', models.ImageField(upload_to='')),
                ('categories', models.ManyToManyField(related_name='events', to='eventFinderApp.Category')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hosting_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
