# Generated by Django 2.2 on 2019-09-14 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventFinderApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='host',
            field=models.CharField(max_length=200),
        ),
    ]
