# Generated by Django 2.2 on 2019-09-07 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventFinderApp', '0002_auto_20190907_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
    ]
